let index = 0;

export const sexList = [
  { key: index++, section: true, label: "Sexo" },
  { key: index++, label: "Masculino", value: "M" },
  { key: index++, label: "Feminino", value: "F" },
];

export const heightList = [
  { key: index++, section: true, label: "Altura" },
  { key: index++, label: "1.40 m", value: 140 },
  { key: index++, label: "1.41 m", value: 141 },
  { key: index++, label: "1.42 m", value: 142 },
  { key: index++, label: "1.43 m", value: 143 },
  { key: index++, label: "1.44 m", value: 144 },
  { key: index++, label: "1.45 m", value: 145 },
  { key: index++, label: "1.46 m", value: 146 },
  { key: index++, label: "1.47 m", value: 147 },
  { key: index++, label: "1.48 m", value: 148 },
  { key: index++, label: "1.49 m", value: 149 },
  { key: index++, label: "1.50 m", value: 150 },
  { key: index++, label: "1.51 m", value: 151 },
  { key: index++, label: "1.52 m", value: 152 },
  { key: index++, label: "1.53 m", value: 153 },
  { key: index++, label: "1.54 m", value: 154 },
  { key: index++, label: "1.55 m", value: 155 },
  { key: index++, label: "1.56 m", value: 156 },
  { key: index++, label: "1.57 m", value: 157 },
  { key: index++, label: "1.58 m", value: 158 },
  { key: index++, label: "1.59 m", value: 159 },
  { key: index++, label: "1.60 m", value: 160 },
  { key: index++, label: "1.61 m", value: 161 },
  { key: index++, label: "1.62 m", value: 162 },
  { key: index++, label: "1.63 m", value: 163 },
  { key: index++, label: "1.64 m", value: 164 },
  { key: index++, label: "1.65 m", value: 165 },
  { key: index++, label: "1.66 m", value: 166 },
  { key: index++, label: "1.67 m", value: 167 },
  { key: index++, label: "1.68 m", value: 168 },
  { key: index++, label: "1.69 m", value: 169 },
  { key: index++, label: "1.70 m", value: 170 },
  { key: index++, label: "1.71 m", value: 171 },
  { key: index++, label: "1.72 m", value: 172 },
  { key: index++, label: "1.73 m", value: 173 },
  { key: index++, label: "1.74 m", value: 174 },
  { key: index++, label: "1.75 m", value: 175 },
  { key: index++, label: "1.76 m", value: 176 },
  { key: index++, label: "1.77 m", value: 177 },
  { key: index++, label: "1.78 m", value: 178 },
  { key: index++, label: "1.79 m", value: 179 },
  { key: index++, label: "1.80 m", value: 180 },
  { key: index++, label: "1.81 m", value: 181 },
  { key: index++, label: "1.82 m", value: 182 },
  { key: index++, label: "1.83 m", value: 183 },
  { key: index++, label: "1.84 m", value: 184 },
  { key: index++, label: "1.85 m", value: 185 },
  { key: index++, label: "1.86 m", value: 186 },
  { key: index++, label: "1.87 m", value: 187 },
  { key: index++, label: "1.88 m", value: 188 },
  { key: index++, label: "1.89 m", value: 189 },
  { key: index++, label: "1.90 m", value: 190 },
  { key: index++, label: "1.91 m", value: 191 },
  { key: index++, label: "1.92 m", value: 192 },
  { key: index++, label: "1.93 m", value: 193 },
  { key: index++, label: "1.94 m", value: 194 },
  { key: index++, label: "1.95 m", value: 195 },
  { key: index++, label: "1.96 m", value: 196 },
  { key: index++, label: "1.97 m", value: 197 },
  { key: index++, label: "1.98 m", value: 198 },
  { key: index++, label: "1.99 m", value: 199 },
  { key: index++, label: "2.00 m", value: 200 },
  { key: index++, label: "2.01 m", value: 201 },
  { key: index++, label: "2.02 m", value: 202 },
  { key: index++, label: "2.03 m", value: 203 },
  { key: index++, label: "2.04 m", value: 204 },
  { key: index++, label: "2.05 m", value: 205 },
  { key: index++, label: "2.06 m", value: 206 },
  { key: index++, label: "2.07 m", value: 207 },
  { key: index++, label: "2.08 m", value: 208 },
  { key: index++, label: "2.09 m", value: 209 },
  { key: index++, label: "2.10 m", value: 210 },
  { key: index++, label: "2.11 m", value: 211 },
  { key: index++, label: "2.12 m", value: 212 },
  { key: index++, label: "2.13 m", value: 213 },
  { key: index++, label: "2.14 m", value: 214 },
  { key: index++, label: "2.15 m", value: 215 },
  { key: index++, label: "2.16 m", value: 216 },
  { key: index++, label: "2.17 m", value: 217 },
  { key: index++, label: "2.18 m", value: 218 },
  { key: index++, label: "2.19 m", value: 219 },
  { key: index++, label: "2.20 m", value: 220 },
];

export const weightList = [
  { key: index++, section: true, label: "Peso" },
  { key: index++, label: "45 Kg", value: 45 },
  { key: index++, label: "46 Kg", value: 46 },
  { key: index++, label: "47 Kg", value: 47 },
  { key: index++, label: "48 Kg", value: 49 },
  { key: index++, label: "49 Kg", value: 49 },
  { key: index++, label: "50 Kg", value: 50 },
  { key: index++, label: "51 Kg", value: 51 },
  { key: index++, label: "52 Kg", value: 52 },
  { key: index++, label: "53 Kg", value: 53 },
  { key: index++, label: "54 Kg", value: 54 },
  { key: index++, label: "55 Kg", value: 55 },
  { key: index++, label: "56 Kg", value: 56 },
  { key: index++, label: "57 Kg", value: 57 },
  { key: index++, label: "58 Kg", value: 58 },
  { key: index++, label: "59 Kg", value: 59 },
  { key: index++, label: "60 Kg", value: 60 },
  { key: index++, label: "61 Kg", value: 61 },
  { key: index++, label: "62 Kg", value: 62 },
  { key: index++, label: "63 Kg", value: 63 },
  { key: index++, label: "64 Kg", value: 64 },
  { key: index++, label: "65 Kg", value: 65 },
  { key: index++, label: "66 Kg", value: 66 },
  { key: index++, label: "67 Kg", value: 67 },
  { key: index++, label: "68 Kg", value: 68 },
  { key: index++, label: "69 Kg", value: 69 },
  { key: index++, label: "70 Kg", value: 70 },
  { key: index++, label: "71 Kg", value: 71 },
  { key: index++, label: "72 Kg", value: 72 },
  { key: index++, label: "73 Kg", value: 73 },
  { key: index++, label: "74 Kg", value: 74 },
  { key: index++, label: "75 Kg", value: 75 },
  { key: index++, label: "76 Kg", value: 76 },
  { key: index++, label: "77 Kg", value: 77 },
  { key: index++, label: "78 Kg", value: 78 },
  { key: index++, label: "79 Kg", value: 79 },
  { key: index++, label: "80 Kg", value: 80 },
  { key: index++, label: "81 Kg", value: 81 },
  { key: index++, label: "82 Kg", value: 82 },
  { key: index++, label: "83 Kg", value: 83 },
  { key: index++, label: "84 Kg", value: 84 },
  { key: index++, label: "85 Kg", value: 85 },
  { key: index++, label: "86 Kg", value: 86 },
  { key: index++, label: "87 Kg", value: 87 },
  { key: index++, label: "88 Kg", value: 88 },
  { key: index++, label: "89 Kg", value: 89 },
  { key: index++, label: "90 Kg", value: 90 },
  { key: index++, label: "91 Kg", value: 91 },
  { key: index++, label: "92 Kg", value: 92 },
  { key: index++, label: "93 Kg", value: 93 },
  { key: index++, label: "94 Kg", value: 94 },
  { key: index++, label: "95 Kg", value: 95 },
  { key: index++, label: "96 Kg", value: 96 },
  { key: index++, label: "97 Kg", value: 97 },
  { key: index++, label: "98 Kg", value: 98 },
  { key: index++, label: "99 Kg", value: 99 },
  { key: index++, label: "100 Kg", value: 100 },
  { key: index++, label: "101 Kg", value: 101 },
  { key: index++, label: "102 Kg", value: 102 },
  { key: index++, label: "103 Kg", value: 103 },
  { key: index++, label: "104 Kg", value: 104 },
  { key: index++, label: "105 Kg", value: 105 },
  { key: index++, label: "106 Kg", value: 106 },
  { key: index++, label: "107 Kg", value: 107 },
  { key: index++, label: "108 Kg", value: 108 },
  { key: index++, label: "109 Kg", value: 109 },
  { key: index++, label: "110 Kg", value: 110 },
  { key: index++, label: "111 Kg", value: 111 },
  { key: index++, label: "112 Kg", value: 112 },
  { key: index++, label: "113 Kg", value: 113 },
  { key: index++, label: "114 Kg", value: 114 },
  { key: index++, label: "115 Kg", value: 115 },
  { key: index++, label: "116 Kg", value: 116 },
  { key: index++, label: "117 Kg", value: 117 },
  { key: index++, label: "118 Kg", value: 118 },
  { key: index++, label: "119 Kg", value: 119 },
  { key: index++, label: "120 Kg", value: 120 },
  { key: index++, label: "121 Kg", value: 121 },
  { key: index++, label: "122 Kg", value: 122 },
  { key: index++, label: "123 Kg", value: 123 },
  { key: index++, label: "124 Kg", value: 124 },
  { key: index++, label: "125 Kg", value: 125 },
  { key: index++, label: "126 Kg", value: 126 },
  { key: index++, label: "127 Kg", value: 127 },
  { key: index++, label: "128 Kg", value: 128 },
  { key: index++, label: "129 Kg", value: 129 },
  { key: index++, label: "130 Kg", value: 130 },
];

export const goalList = [
  { key: index++, section: true, label: "Objetivo" },
  { key: index++, label: "Perder Peso", value: "P" },
  { key: index++, label: "Hipertrofia", value: "G" },
];

export const gymAvail = [
  { key: index++, label: "Sim", value: "GYM-S" },
  { key: index++, label: "Não", value: "GYM-N" },
];

export const gymFreq = [
  { key: index++, label: "Sim", value: "GYM-FREQ-S" },
  { key: index++, label: "Não", value: "GYM-FREQ-N" },
];

export const userRes = [
  { key: index++, label: "Sem restrição", value: "RES-N" },
  { key: index++, label: "Intolerancia à Lactose", value: "RES-LAC" },
  { key: index++, label: "Restrição de Glúten", value: "RES-GLU" },
];
